# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.proto import collaboration_pb2 as services_dot_proto_dot_collaboration__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services/proto/collaboration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollaborationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDocument = channel.unary_unary(
                '/collabdocs.v1.CollaborationService/CreateDocument',
                request_serializer=services_dot_proto_dot_collaboration__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=services_dot_proto_dot_collaboration__pb2.Document.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/collabdocs.v1.CollaborationService/ListDocuments',
                request_serializer=services_dot_proto_dot_collaboration__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=services_dot_proto_dot_collaboration__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/collabdocs.v1.CollaborationService/GetDocument',
                request_serializer=services_dot_proto_dot_collaboration__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=services_dot_proto_dot_collaboration__pb2.Document.FromString,
                _registered_method=True)
        self.SetSharing = channel.unary_unary(
                '/collabdocs.v1.CollaborationService/SetSharing',
                request_serializer=services_dot_proto_dot_collaboration__pb2.SetSharingRequest.SerializeToString,
                response_deserializer=services_dot_proto_dot_collaboration__pb2.Document.FromString,
                _registered_method=True)
        self.Sync = channel.stream_stream(
                '/collabdocs.v1.CollaborationService/Sync',
                request_serializer=services_dot_proto_dot_collaboration__pb2.ClientEvent.SerializeToString,
                response_deserializer=services_dot_proto_dot_collaboration__pb2.ServerEvent.FromString,
                _registered_method=True)


class CollaborationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSharing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollaborationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=services_dot_proto_dot_collaboration__pb2.CreateDocumentRequest.FromString,
                    response_serializer=services_dot_proto_dot_collaboration__pb2.Document.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=services_dot_proto_dot_collaboration__pb2.ListDocumentsRequest.FromString,
                    response_serializer=services_dot_proto_dot_collaboration__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=services_dot_proto_dot_collaboration__pb2.GetDocumentRequest.FromString,
                    response_serializer=services_dot_proto_dot_collaboration__pb2.Document.SerializeToString,
            ),
            'SetSharing': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSharing,
                    request_deserializer=services_dot_proto_dot_collaboration__pb2.SetSharingRequest.FromString,
                    response_serializer=services_dot_proto_dot_collaboration__pb2.Document.SerializeToString,
            ),
            'Sync': grpc.stream_stream_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=services_dot_proto_dot_collaboration__pb2.ClientEvent.FromString,
                    response_serializer=services_dot_proto_dot_collaboration__pb2.ServerEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collabdocs.v1.CollaborationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collabdocs.v1.CollaborationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollaborationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.v1.CollaborationService/CreateDocument',
            services_dot_proto_dot_collaboration__pb2.CreateDocumentRequest.SerializeToString,
            services_dot_proto_dot_collaboration__pb2.Document.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.v1.CollaborationService/ListDocuments',
            services_dot_proto_dot_collaboration__pb2.ListDocumentsRequest.SerializeToString,
            services_dot_proto_dot_collaboration__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.v1.CollaborationService/GetDocument',
            services_dot_proto_dot_collaboration__pb2.GetDocumentRequest.SerializeToString,
            services_dot_proto_dot_collaboration__pb2.Document.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSharing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.v1.CollaborationService/SetSharing',
            services_dot_proto_dot_collaboration__pb2.SetSharingRequest.SerializeToString,
            services_dot_proto_dot_collaboration__pb2.Document.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/collabdocs.v1.CollaborationService/Sync',
            services_dot_proto_dot_collaboration__pb2.ClientEvent.SerializeToString,
            services_dot_proto_dot_collaboration__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
