# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/proto/llm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'services/proto/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18services/proto/llm.proto\x12\x11\x63ollabdocs.llm.v1\"W\n\x0f\x43ompleteRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06prefix\x18\x03 \x01(\t\x12\x0e\n\x06suffix\x18\x04 \x01(\t\"D\n\x0eSummaryRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\x1f\n\rSummaryJobRef\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"G\n\x0fSummaryJobQuery\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\"_\n\x10SummaryJobStatus\x12.\n\x05state\x18\x01 \x01(\x0e\x32\x1f.collabdocs.llm.v1.SummaryState\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"D\n\x0e\x45nhanceRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\x1a\n\nTextResult\x12\x0c\n\x04text\x18\x01 \x01(\t*\x98\x01\n\x0cSummaryState\x12\x1d\n\x19SUMMARY_STATE_UNSPECIFIED\x10\x00\x12\x18\n\x14SUMMARY_STATE_QUEUED\x10\x01\x12\x19\n\x15SUMMARY_STATE_RUNNING\x10\x02\x12\x1a\n\x16SUMMARY_STATE_COMPLETE\x10\x03\x12\x18\n\x14SUMMARY_STATE_FAILED\x10\x04\x32\xd7\x02\n\nLlmService\x12M\n\x08\x43omplete\x12\".collabdocs.llm.v1.CompleteRequest\x1a\x1d.collabdocs.llm.v1.TextResult\x12S\n\x0cStartSummary\x12!.collabdocs.llm.v1.SummaryRequest\x1a .collabdocs.llm.v1.SummaryJobRef\x12X\n\rGetSummaryJob\x12\".collabdocs.llm.v1.SummaryJobQuery\x1a#.collabdocs.llm.v1.SummaryJobStatus\x12K\n\x07\x45nhance\x12!.collabdocs.llm.v1.EnhanceRequest\x1a\x1d.collabdocs.llm.v1.TextResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.proto.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARYSTATE']._serialized_start=508
  _globals['_SUMMARYSTATE']._serialized_end=660
  _globals['_COMPLETEREQUEST']._serialized_start=47
  _globals['_COMPLETEREQUEST']._serialized_end=134
  _globals['_SUMMARYREQUEST']._serialized_start=136
  _globals['_SUMMARYREQUEST']._serialized_end=204
  _globals['_SUMMARYJOBREF']._serialized_start=206
  _globals['_SUMMARYJOBREF']._serialized_end=237
  _globals['_SUMMARYJOBQUERY']._serialized_start=239
  _globals['_SUMMARYJOBQUERY']._serialized_end=310
  _globals['_SUMMARYJOBSTATUS']._serialized_start=312
  _globals['_SUMMARYJOBSTATUS']._serialized_end=407
  _globals['_ENHANCEREQUEST']._serialized_start=409
  _globals['_ENHANCEREQUEST']._serialized_end=477
  _globals['_TEXTRESULT']._serialized_start=479
  _globals['_TEXTRESULT']._serialized_end=505
  _globals['_LLMSERVICE']._serialized_start=663
  _globals['_LLMSERVICE']._serialized_end=1006
# @@protoc_insertion_point(module_scope)
