# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.proto import llm_pb2 as services_dot_proto_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services/proto/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/collabdocs.llm.v1.LlmService/Complete',
                request_serializer=services_dot_proto_dot_llm__pb2.CompleteRequest.SerializeToString,
                response_deserializer=services_dot_proto_dot_llm__pb2.TextResult.FromString,
                _registered_method=True)
        self.StartSummary = channel.unary_unary(
                '/collabdocs.llm.v1.LlmService/StartSummary',
                request_serializer=services_dot_proto_dot_llm__pb2.SummaryRequest.SerializeToString,
                response_deserializer=services_dot_proto_dot_llm__pb2.SummaryJobRef.FromString,
                _registered_method=True)
        self.GetSummaryJob = channel.unary_unary(
                '/collabdocs.llm.v1.LlmService/GetSummaryJob',
                request_serializer=services_dot_proto_dot_llm__pb2.SummaryJobQuery.SerializeToString,
                response_deserializer=services_dot_proto_dot_llm__pb2.SummaryJobStatus.FromString,
                _registered_method=True)
        self.StartEnhancement = channel.unary_unary(
                '/collabdocs.llm.v1.LlmService/StartEnhancement',
                request_serializer=services_dot_proto_dot_llm__pb2.EnhanceRequest.SerializeToString,
                response_deserializer=services_dot_proto_dot_llm__pb2.EnhancementJobRef.FromString,
                _registered_method=True)
        self.GetEnhancementJob = channel.unary_unary(
                '/collabdocs.llm.v1.LlmService/GetEnhancementJob',
                request_serializer=services_dot_proto_dot_llm__pb2.EnhancementJobQuery.SerializeToString,
                response_deserializer=services_dot_proto_dot_llm__pb2.EnhancementJobStatus.FromString,
                _registered_method=True)


class LlmServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummaryJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartEnhancement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnhancementJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=services_dot_proto_dot_llm__pb2.CompleteRequest.FromString,
                    response_serializer=services_dot_proto_dot_llm__pb2.TextResult.SerializeToString,
            ),
            'StartSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSummary,
                    request_deserializer=services_dot_proto_dot_llm__pb2.SummaryRequest.FromString,
                    response_serializer=services_dot_proto_dot_llm__pb2.SummaryJobRef.SerializeToString,
            ),
            'GetSummaryJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummaryJob,
                    request_deserializer=services_dot_proto_dot_llm__pb2.SummaryJobQuery.FromString,
                    response_serializer=services_dot_proto_dot_llm__pb2.SummaryJobStatus.SerializeToString,
            ),
            'StartEnhancement': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEnhancement,
                    request_deserializer=services_dot_proto_dot_llm__pb2.EnhanceRequest.FromString,
                    response_serializer=services_dot_proto_dot_llm__pb2.EnhancementJobRef.SerializeToString,
            ),
            'GetEnhancementJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnhancementJob,
                    request_deserializer=services_dot_proto_dot_llm__pb2.EnhancementJobQuery.FromString,
                    response_serializer=services_dot_proto_dot_llm__pb2.EnhancementJobStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collabdocs.llm.v1.LlmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collabdocs.llm.v1.LlmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.llm.v1.LlmService/Complete',
            services_dot_proto_dot_llm__pb2.CompleteRequest.SerializeToString,
            services_dot_proto_dot_llm__pb2.TextResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.llm.v1.LlmService/StartSummary',
            services_dot_proto_dot_llm__pb2.SummaryRequest.SerializeToString,
            services_dot_proto_dot_llm__pb2.SummaryJobRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummaryJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.llm.v1.LlmService/GetSummaryJob',
            services_dot_proto_dot_llm__pb2.SummaryJobQuery.SerializeToString,
            services_dot_proto_dot_llm__pb2.SummaryJobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartEnhancement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.llm.v1.LlmService/StartEnhancement',
            services_dot_proto_dot_llm__pb2.EnhanceRequest.SerializeToString,
            services_dot_proto_dot_llm__pb2.EnhancementJobRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnhancementJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdocs.llm.v1.LlmService/GetEnhancementJob',
            services_dot_proto_dot_llm__pb2.EnhancementJobQuery.SerializeToString,
            services_dot_proto_dot_llm__pb2.EnhancementJobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
